const Map<String, String> arStrings = {
  'appTitle': 'مرافق المركبة الكهربائية',
  'welcomeBack': 'مرحباً بعودتك',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'guest': 'الدخول كضيف',
  'dashboard': 'الرئيسية',
  'quickControls': 'التحكم السريع',
  'energy': 'الطاقة',
  'trips': 'الرحلات',
  'profile': 'الملف الشخصي',
  'settings': 'الإعدادات',
  'catalog': 'الدليل',
  'stations': 'المحطات',
  'maintenance': 'الصيانة',
  'help': 'المساعدة والتعريف',
  'garage': 'المرآب',
  'garageManage': 'إدارة المرآب',
  'garageSubtitle': 'بدّل المركبات، عدّل الإحصاءات، وثبّت المفضلة.',
  'activityCenter': 'مركز الأنشطة',
  'activitySubtitle':
      'راقب الشحن والرحلات والصيانة والتنبيهات في مكان واحد.',
  'activityTimeline': 'موجز الأنشطة',
  'activityFilters': 'عوامل التصفية',
  'activityPinned': 'عناصر مثبتة',
  'activityOpenOnly': 'عرض العناصر المفتوحة فقط',
  'activityCharging': 'الشحن',
  'activityTrips': 'الرحلات',
  'activityMaintenance': 'الصيانة',
  'activityEnergy': 'الطاقة',
  'activityAlerts': 'التنبيهات والنظام',
  'activityOpen': 'عناصر مفتوحة',
  'activityResolvedLabel': 'مغلقة',
  'activityEmpty': 'لا توجد عناصر متطابقة مع عوامل التصفية الحالية.',
  'globalSearch': 'البحث الشامل',
  'searchEverything': 'ابحث في السيارات والرحلات والمحطات…',
  'all': 'الكل',
  'vehicles': 'المركبات',
  'results': 'النتائج',
  'viewAll': 'عرض الكل',
  'noResults': 'لا توجد نتائج حالياً',
  'recentSearches': 'اقتراحات سريعة',
  'compare': 'مقارنة',
  'language': 'اللغة',
  'theme': 'السمة',
  'systemTheme': 'حسب النظام',
  'lightTheme': 'فاتحة',
  'darkTheme': 'داكنة',
  'primaryColor': 'اللون الأساسي',
  'units': 'الوحدات',
  'metricUnits': 'استخدام النظام المتري',
  'celsiusUnits': 'عرض الحرارة بالسيلسيوس',
  'notifications': 'الإشعارات',
  'generalNotifications': 'إشعارات عامة',
  'chargingAlerts': 'تنبيهات الشحن',
  'maintenanceReminders': 'تذكيرات الصيانة',
  'generateReport': 'توليد تقرير دون اتصال',
  'close': 'إغلاق',
  'markResolved': 'وضع كمكتمل',
  'reopen': 'إعادة فتح',
  'logout': 'تسجيل الخروج',
  'addVehicle': 'إضافة مركبة',
  'editVehicle': 'تعديل المركبة',
  'range': 'المدى',
  'power': 'القوة',
  'battery': 'البطارية',
  'odometer': 'عداد المسافة',
  'efficiency': 'الكفاءة',
  'drivetrain': 'نظام الدفع',
  'vehicleHealth': 'صحة المركبة',
  'diagnostics': 'التشخيص الذكي',
  'diagnosticsSubtitle': 'تنبأ بأعطال الأنظمة واضبط صحتها واستعد للصيانة مبكراً.',
  'diagnosticsFilterAll': 'كل الأنظمة',
  'diagnosticsBattery': 'البطارية',
  'diagnosticsCharging': 'الشحن',
  'diagnosticsTires': 'الإطارات',
  'diagnosticsClimate': 'المناخ',
  'diagnosticsSoftware': 'البرمجيات',
  'diagnosticsBrakes': 'الفرامل',
  'diagnosticsTimeline': 'الخط الزمني التنبؤي',
  'diagnosticsNoReports': 'جميع الأنظمة مستقرة حالياً.',
  'diagnosticsNoTimeline': 'لا توجد أحداث متوقعة خلال ٤٨ ساعة.',
  'diagnosticsRecommendations': 'التوصيات',
  'diagnosticsPredictiveAlerts': 'تنبيهات تنبؤية',
  'diagnosticsAutoSchedule': 'جدولة الصيانة تلقائياً',
  'diagnosticsStatusGood': 'مستقر',
  'diagnosticsStatusMonitor': 'تحت المراقبة',
  'diagnosticsStatusAction': 'يتطلب إجراء',
  'diagnosticsAiExplainer':
      'سيتم قريباً تفعيل تشخيصات الذكاء الاصطناعي والفحص عن بعد ومحادثة الخبراء.',
  'diagnosticsRecBatteryCells': 'وازن الخلايا في جلسة الشحن القادمة',
  'diagnosticsRecBatteryPrecondition': 'هيئ البطارية قبل الرحلات الطويلة',
  'diagnosticsRecChargingSchedule': 'انقل الشحن إلى أوقات خارج الذروة',
  'diagnosticsRecTirePressure': 'عدّل ضغط الإطارات قريباً',
  'diagnosticsRecSoftwareUpdate': 'جدول تحديث برمجيات المقصورة',
  'diagnosticsRecClimateFilter': 'استبدل فلتر المقصورة قريباً',
  'diagnosticsRecBrakeBleed': 'قم بتفريغ زيت الفرامل في الزيارة القادمة',
  'diagnosticsRecBrakePads': 'افحص وسادات الفرامل الأمامية',
  'diagnosticsMetricCellBalance': 'توازن الخلايا',
  'diagnosticsMetricPackTemp': 'حرارة البطارية',
  'diagnosticsMetricChargeLimit': 'حد الشحن',
  'diagnosticsMetricSessionDrift': 'انحراف الجلسة',
  'diagnosticsMetricPressureFront': 'ضغط أمامي',
  'diagnosticsMetricPressureRear': 'ضغط خلفي',
  'diagnosticsMetricVersion': 'إصدار البرمجيات',
  'diagnosticsMetricUpdateAge': 'أيام منذ التحديث',
  'diagnosticsMetricFilter': 'عمر الفلتر',
  'diagnosticsMetricHumidity': 'رطوبة المقصورة',
  'diagnosticsMetricPadWear': 'تآكل الوسادات',
  'diagnosticsMetricFluidQuality': 'جودة السائل',
  'diagnosticsEventBatteryTitle': 'تنبيه نافذة حرارية',
  'diagnosticsEventBatteryDetail': 'سترتفع حرارة الحزمة في الشحن السريع القادم. ينصح بالتهيئة.',
  'diagnosticsEventTiresTitle': 'انخفاض ضغط الإطارات',
  'diagnosticsEventTiresDetail': 'الإطارات الخلفية تنخفض بمقدار ٢ psi. خطط لتعبئة سريعة.',
  'diagnosticsEventSoftwareTitle': 'تحديث برمجي مجدول',
  'diagnosticsEventSoftwareDetail': 'سيتم تنزيل إصدار المقصورة 11.3 الليلة.',
  'diagnosticsEventBrakesTitle': 'تذكير خدمة الفرامل',
  'diagnosticsEventBrakesDetail': 'وسادات الفرامل الأمامية تقترب من ٥٠٪. أضفها للصيانة.',
  'diagnosticsBatterySummary': 'الخلايا متوازنة مع انحراف حراري طفيف.',
  'diagnosticsChargingSummary': 'جلسات الشحن تُظهر انحرافاً قرب حد ٨٠٪.',
  'diagnosticsTiresSummary': 'الإطارات الخلفية تميل للانخفاض مع برودة الجو.',
  'diagnosticsClimateSummary': 'فلتر المقصورة يقترب من نهايته لكن التدفق مستقر.',
  'diagnosticsSoftwareSummary': 'برمجيات المقصورة محدثة مع رقعة بسيطة قادمة.',
  'diagnosticsBrakesSummary': 'تآكل الوسادات ضمن الحد لكن السائل يحتاج متابعة.',
  'systemsHealth': 'صحة الأنظمة',
  'criticalIssues': 'تنبيهات حرجة',
  'lastScan': 'آخر فحص',
  'runScan': 'تشغيل فحص ذكي',
  'viewDiagnostics': 'عرض التشخيص',
  'lastService': 'آخر صيانة',
  'favoriteVehicles': 'المركبات المفضلة',
  'noFavoritesYet': 'قم بوضع علامة مفضلة لعرض الاختصارات هنا.',
  'setPrimary': 'تعيين كمركبة أساسية',
  'primaryVehicle': 'المركبة الأساسية',
  'allVehicles': 'جميع المركبات',
  'save': 'حفظ',
  'insights': 'الرؤى والمدرب',
  'insightsSubtitle':
      'تابع الكفاءة وعادات الشحن واقتراحات الذكاء الاصطناعي في مكان واحد.',
  'insightHighlights': 'أهم الرؤى',
  'insightPinned': 'رؤى مثبتة',
  'insightCoaching': 'مدرب القيادة',
  'insightTrends': 'اتجاه الكفاءة الأسبوعي',
  'insightEnergyMix': 'مزيج الطاقة',
  'insightAction': 'الإجراء الموصى به',
  'insightAcknowledge': 'تأكيد',
  'insightRefreshHint': 'اسحب للأسفل لمحاكاة تحليلات ونصائح جديدة.',
  'insightEmpty': 'لا توجد رؤى مطابقة لعوامل التصفية الحالية.',
  'insightCategoryEfficiency': 'الكفاءة',
  'insightCategoryCharging': 'الشحن',
  'insightCategoryTrips': 'الرحلات',
  'insightCategoryMaintenance': 'الصيانة',
  'insightCategoryDriving': 'الراحة والمناخ',
  'viewInsights': 'فتح الرؤى',
  'remove': 'إزالة',
};
