const Map<String, String> enStrings = {
  'appTitle': 'EV Smart Companion',
  'welcomeBack': 'Welcome back',
  'login': 'Login',
  'register': 'Register',
  'guest': 'Continue as guest',
  'dashboard': 'Dashboard',
  'quickControls': 'Quick Controls',
  'energy': 'Energy',
  'trips': 'Trips',
  'profile': 'Profile',
  'settings': 'Settings',
  'catalog': 'Catalog',
  'stations': 'Stations',
  'maintenance': 'Maintenance',
  'help': 'Help & About',
  'garage': 'Garage',
  'garageManage': 'Open garage',
  'garageSubtitle': 'Switch EVs, update stats, and pin your favorites.',
  'globalSearch': 'Global search',
  'searchEverything': 'Search vehicles, trips, stations…',
  'all': 'All',
  'vehicles': 'Vehicles',
  'results': 'Results',
  'noResults': 'No matches yet',
  'recentSearches': 'Quick picks',
  'compare': 'Compare',
  'language': 'Language',
  'theme': 'Theme',
  'systemTheme': 'System default',
  'lightTheme': 'Light',
  'darkTheme': 'Dark',
  'primaryColor': 'Primary color',
  'units': 'Units',
  'metricUnits': 'Use metric units',
  'celsiusUnits': 'Use Celsius degrees',
  'notifications': 'Notifications',
  'generalNotifications': 'General notifications',
  'chargingAlerts': 'Charging alerts',
  'maintenanceReminders': 'Maintenance reminders',
  'logout': 'Logout',
  'addVehicle': 'Add vehicle',
  'editVehicle': 'Edit vehicle',
  'range': 'Range',
  'power': 'Power',
  'battery': 'Battery',
  'odometer': 'Odometer',
  'efficiency': 'Efficiency',
  'drivetrain': 'Drivetrain',
  'vehicleHealth': 'Vehicle health',
  'lastService': 'Last service',
  'favoriteVehicles': 'Favorite vehicles',
  'noFavoritesYet': 'Mark vehicles as favorite to show quick actions here.',
  'setPrimary': 'Set as primary',
  'primaryVehicle': 'Primary vehicle',
  'allVehicles': 'All vehicles',
  'save': 'Save',
};
