const Map<String, String> enStrings = {
  'appTitle': 'EV Smart Companion',
  'welcomeBack': 'Welcome back',
  'login': 'Login',
  'register': 'Register',
  'guest': 'Continue as guest',
  'dashboard': 'Dashboard',
  'quickControls': 'Quick Controls',
  'trips': 'Trips',
  'profile': 'Profile',
  'settings': 'Settings',
  'catalog': 'Catalog',
  'compare': 'Compare',
  'language': 'Language',
  'theme': 'Theme',
  'primaryColor': 'Primary color',
  'units': 'Units',
  'notifications': 'Notifications',
  'logout': 'Logout',
};
