const Map<String, String> arStrings = {
  'appTitle': 'مرافق المركبة الكهربائية',
  'welcomeBack': 'مرحباً بعودتك',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'guest': 'الدخول كضيف',
  'dashboard': 'الرئيسية',
  'quickControls': 'التحكم السريع',
  'energy': 'الطاقة',
  'trips': 'الرحلات',
  'profile': 'الملف الشخصي',
  'settings': 'الإعدادات',
  'catalog': 'الدليل',
  'stations': 'المحطات',
  'maintenance': 'الصيانة',
  'help': 'المساعدة والتعريف',
  'garage': 'المرآب',
  'garageManage': 'إدارة المرآب',
  'garageSubtitle': 'بدّل المركبات، عدّل الإحصاءات، وثبّت المفضلة.',
  'globalSearch': 'البحث الشامل',
  'searchEverything': 'ابحث في السيارات والرحلات والمحطات…',
  'all': 'الكل',
  'vehicles': 'المركبات',
  'results': 'النتائج',
  'noResults': 'لا توجد نتائج حالياً',
  'recentSearches': 'اقتراحات سريعة',
  'compare': 'مقارنة',
  'language': 'اللغة',
  'theme': 'السمة',
  'systemTheme': 'حسب النظام',
  'lightTheme': 'فاتحة',
  'darkTheme': 'داكنة',
  'primaryColor': 'اللون الأساسي',
  'units': 'الوحدات',
  'metricUnits': 'استخدام النظام المتري',
  'celsiusUnits': 'عرض الحرارة بالسيلسيوس',
  'notifications': 'الإشعارات',
  'generalNotifications': 'إشعارات عامة',
  'chargingAlerts': 'تنبيهات الشحن',
  'maintenanceReminders': 'تذكيرات الصيانة',
  'logout': 'تسجيل الخروج',
  'addVehicle': 'إضافة مركبة',
  'editVehicle': 'تعديل المركبة',
  'range': 'المدى',
  'power': 'القوة',
  'battery': 'البطارية',
  'odometer': 'عداد المسافة',
  'efficiency': 'الكفاءة',
  'drivetrain': 'نظام الدفع',
  'vehicleHealth': 'صحة المركبة',
  'lastService': 'آخر صيانة',
  'favoriteVehicles': 'المركبات المفضلة',
  'noFavoritesYet': 'قم بوضع علامة مفضلة لعرض الاختصارات هنا.',
  'setPrimary': 'تعيين كمركبة أساسية',
  'primaryVehicle': 'المركبة الأساسية',
  'allVehicles': 'جميع المركبات',
  'save': 'حفظ',
};
