const Map<String, String> arStrings = {
  'appTitle': 'مرافق المركبة الكهربائية',
  'welcomeBack': 'مرحباً بعودتك',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'guest': 'الدخول كضيف',
  'dashboard': 'الرئيسية',
  'quickControls': 'التحكم السريع',
  'trips': 'الرحلات',
  'profile': 'الملف الشخصي',
  'settings': 'الإعدادات',
  'catalog': 'الدليل',
  'compare': 'مقارنة',
  'language': 'اللغة',
  'theme': 'السمة',
  'primaryColor': 'اللون الأساسي',
  'units': 'الوحدات',
  'notifications': 'الإشعارات',
  'logout': 'تسجيل الخروج',
};
